#!/usr/bin/python

from palaso.contexts import defaultapp, relaxedsubs, utf8out
from palaso.kmn.coverage import Coverage
import sys
import contextlib

with defaultapp() :
    k = Coverage(sys.argv[1])
    mode = sys.argv[2] if len(sys.argv) > 2 else 'all'
    results = sorted(sorted(k.coverage_test(mode)),key=len,reverse=True)
    sys.stdout.writelines(l + '\n' for l in results)
