#!/usr/bin/python

import codecs
from palaso.font.shape import make_shaper
from optparse import OptionParser
from fontTools.ttLib import TTFont
import sys, os

def roundpt(pt, res) :
    try :
        return(int(pt[0] / res) * res, int(pt[1] / res) * res)
    except ValueError :
        pass
    return (0, 0)

def name(tt, gl) :
    return (tt.getGlyphName(gl[0]), roundpt(gl[1], 0.1))


def logstart(f, fpath, args) :
    f.write("""<html><head>
<meta charset="UTF8"/>
<style>
    @font-face {
        family: testfont;
        source: url(%s);
    }
    .text {
        font-family: testfont;
    }
    .info {
        font-family: monospace;
        vertical-align: text-top;
    }
</style></head><body><table>
""")
    if args.label is not None and len(args.label) :
        f.write("<tr><th></th><th></th><th>%s</th></tr>\n" % ("</th><th>".join(args.label)))

def logentry(f, line, word, string, lglyphs, rglyphs) :
    f.write("<tr><td>%d.%d</td><td class='text'>%s</td><td class='info'>%s</td><td class='info'>%s</td></tr>\n" %
                (line, word, string, "<br/>".join(map(repr, lglyphs)), "<br/>".join(map(repr, rglyphs))))

def logend(f) :
    f.write("</body></html>\n");

parser = OptionParser(usage = '%prog [options] infont1 infont2')
parser.add_option("-t","--text",help="text file to test each line from")
parser.add_option("-o","--output",help="file to log results to")
parser.add_option("-f","--feat",action="append",help="id=value pairs, may be repeated")
parser.add_option("-e","--engine",default='gr',help="renderer to use [gr]")
parser.add_option("-l","--lang",help="language to tag text with")
parser.add_option("-s","--script",help="script of text")
parser.add_option("-r","--rtl",action="store_true",help="right to left")
parser.add_option("-k","--keep",action="store_true",help="keep going, don't return error count")
parser.add_option("-p","--split",action="store_true",help="Split on spaces")
parser.add_option("-L","--label",action="append",help="report font labels")
(opts, args) = parser.parse_args()

if not opts.lang : opts.lang = 0
if not opts.script : opts.script = 0
if not opts.rtl : opts.rtl = 0
if opts.output :
    outfile = codecs.open(opts.output, mode="w", encoding="utf_8")
else :
#    outfile = codecs.EncodedFile(sys.stdout, "unicode_internal", file_encoding="utf_8")
    outfile = codecs.getwriter("utf_8")(sys.stdout)

feats = {}
if opts.feat :
    for f in opts.feat :
        k, v = f.split('=')
        feats[k.strip()] = int(v.strip())

font1 = make_shaper(opts.engine, args[0], 12, opts.rtl, feats, opts.script, opts.lang)
fpath1 = os.path.relpath(args[0], start=(os.path.dirname(opts.output) if opts.output else '.'))
tt1 = TTFont(args[0])
if len(args) > 1 :
    font2 = make_shaper(opts.engine, args[1], 12, opts.rtl, feats, opts.script, opts.lang)
    tt2 = TTFont(args[1])
f = codecs.open(opts.text, encoding="utf_8")

count = 0
errors = 0
logstarted = False
for l in f.readlines() :
    count += 1
    l = l.strip()
    if opts.split :
        words = l.split()
    else :
        words = (l, )
    wcount = 0
    for s in words :
        wcount += 1
        gl1 = map(lambda x: name(tt1, x), font1.glyphs(s))
        if len(args) > 1 :
            gl2 = map(lambda x: name(tt2, x), font2.glyphs(s))
        else :
            gl2 = []
        if gl1 != gl2 :
            if not logstarted :
                logstart(outfile, fpath1, opts)
                logstarted = True
            logentry(outfile, count, wcount, s, gl1, gl2)
            errors += 1
if logstarted : logend(outfile)
outfile.close()
sys.exit(0 if opts.keep else errors)

