#!/usr/bin/env python3
'''
Run the USFM parser over a project generating a report of all the parsing
errors found for each SFM file in the project.

Automatically load the usfm.sty and custom.sty stylesheets if present
'''
from palaso.sfm import usfm, style
from itertools import chain
import argparse
import codecs
import functools
from pathlib import Path
import warnings

__version__ = '0.1'
__date__ = '22 Nov 2019'
__author__ = 'Tim Eves <tim_eves@sil.org>'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "project", metavar="PARATEXT-PROJECT", type=Path,
        help="Path to Paratext project folder")
    parser.add_argument(
        "sfms", metavar="SFM", type=str, nargs='*',
        default=['*.SFM'],
        help="SFMs to be parsed. default: %(default)s")
    parser.add_argument(
        "-s", "--strict", dest='error_level',
        action='store_const', const=usfm.level.Marker,
        default=usfm.level.Unrecoverable,
        help='Turn on strict parsing mode. Markers not in the stylesheet or '
             'private name space will cause an error')
    parser.add_argument(
        "--no-project-sty", dest="stylesheet",
        action='store_const', const=[],
        default=[p for p in (Path('usfm.sty'), Path('custom.sty'))
                 if p.exists()],
        help="Do not load per-project usfm.sty or custom.sty style sheets. "
             "Default behaviour is to attempt to load usfm.sty and "
             "custom.sty if present")
    parser.add_argument(
        "-S", "--stylesheet", metavar='STY-FILE', type=Path, action='append',
        help='Add this stylesheet to add/override marker definitions to the '
             'default USFM, project or custom stylesheets. Multiple uses of '
             'this option will see stylesheets applied in the order '
             'specified.')

    args = parser.parse_args()
    if not args.project.exists():
        parser.error('missing Paratext project directory.')

    args.sfms = list(chain.from_iterable(args.project.glob(g)
                                         for g in args.sfms))
    if not args.sfms:
        parser.error("no SFM files found to check.")

    try:
        stylesheet = functools.reduce(
            lambda a, s: a.update(s),
            (style.parse((args.project / p).open()) for p in args.stylesheet),
            usfm.default_stylesheet.copy())
    except SyntaxError as err:
        parser.exit(3, f'{parser.prog}: Style sheet parsing error: {err!s}\n')

    with warnings.catch_warnings(record=True) as warns:
        warnings.simplefilter("always", SyntaxWarning)
        try:
            for sfm in args.sfms:
                with codecs.open(sfm, 'r', encoding='utf_8_sig') as source:
                    for _ in usfm.parser(source,
                                         stylesheet=stylesheet,
                                         error_level=args.error_level):
                        pass
        except SyntaxError as err:
            for issue in warns:
                print(issue.message)
            print(err)
        except IOError as err:
            parser.exit(4, f'{parser.prog}: IO error: {err!s}\n')
        else:
            for issue in warns:
                print(issue.message)
