#!/usr/bin/python

import urllib, ConfigParser, os
from optparse import OptionParser
from palaso.debian.sources import source_collection, getdistro, getbasever

p = OptionParser(usage = "%prog [options] repo_url")
p.set_defaults(distro = getdistro(), section = "main")
p.add_option('-a', '--arch', help = 'Architecture to build for')
p.add_option('-d', '--distro', help = 'distribution')
p.add_option('-e', '--edits', help = 'config file giving control values per package')
p.add_option('-n', '--newdistro', help = 'new distribution')
p.add_option('-p', '--put' , help = 'dput target')
p.add_option('-s', '--section', help = 'distribution section to process')
(opts, args) = p.parse_args()
host = args[0]

url = host + "/dists/" + opts.distro + "/" + opts.section + "/source/Sources"
f = urllib.urlopen(url)
x = source_collection(f)
f.close()

try :
    f = urllib.urlopen(host + "/dists/" + opts.newdistro + "/" + opts.section + "/source/Sources")
except IOError :
    f = file("/dev/null")

y = source_collection(f)
f.close()

edits = ConfigParser.ConfigParser()
if opts.edits :
    edits.read(opts.edits)
    
for s in x.sources :
    if s in y.sources : continue
    src = x.sources[s]
    v = src['version']
    if edits.has_option(s, 'Version') :
        v = edits.get(s, 'Version') 
    newv = v.replace(opts.distro, opts.newdistro)
    if newv == v :
        newv = v + "-" + opts.newdistro + "1"
    basever = getbasever(v)
    print "%s: %s(%s) -> %s" % (s, v, basever, newv)
    dir = "%s-%s" % (s, basever)
    x.download(s, dir, host)
    os.chdir(dir)
    cmd = "dch --force-distribution -v " + newv + " -D " + opts.newdistro + " -m 'Transfer from " + opts.distro + "'"
    print cmd
    os.system(cmd)
    os.chdir("..")
    dir = "%s-%s" % (s, getbasever(newv))
    cmd = "dpkg-source"
    if edits.has_section(s) :
        for e in edits.items(s) :
            if e[0].lower() != 'version' :
                cmd += " -D%s='%s'" % e
    cmd += " -b " + dir
    print cmd
    if os.system(cmd) == 0 :
        changes = "%s_%s_source.changes" % (s, newv)
        os.chdir(dir)
        cmd = "dpkg-genchanges -sa -S > ../" + changes
        os.system(cmd)
        os.chdir('..')
        cmd = "debsign " + changes
        os.system(cmd)
        cmd = "dput " + opts.put + " " + changes
        print cmd
        os.system(cmd)
    else :
        print "ERROR: BUILD %s FAILED" % s
    os.system("rm -fr " + dir)

