Document: python-palaso
Title: Debian python-palaso Manual
Author: <insert document author here>
Abstract: This manual describes what python-palaso is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-palaso/python-palaso.sgml.gz

Format: postscript
Files: /usr/share/doc/python-palaso/python-palaso.ps.gz

Format: text
Files: /usr/share/doc/python-palaso/python-palaso.text.gz

Format: HTML
Index: /usr/share/doc/python-palaso/html/index.html
Files: /usr/share/doc/python-palaso/html/*.html


