debian/python3-pypapk/usr/lib/python3.6/dist-packages/palaso/{collation,text,sldr,unicode,{langtags,reggen}.py} usr/lib/python3.6/dist-packages/palaso/
#debian/python3-pypapk/usr/lib/python3.7/dist-packages/palaso/{collation,text,sldr,unicode,{langtags,reggen}.py} usr/lib/python3.7/dist-packages/palaso/
debian/python3-pypapk/usr/bin/{brktest,flattenldml,getclip,ldml2icu,sortldml,sort_trainer,testldml} usr/bin
