#!/usr/bin/python

import gtk
import pprint
import sys

clipboard = gtk.clipboard_get()
text = unicode(clipboard.wait_for_text())
if (len(sys.argv) > 1 and sys.argv[1] == "-p") :
    pprint.pprint(text)
elif (len(sys.argv) > 1 and sys.argv[1] == "-s") :
    for s in text :
        print "%04X" % (ord(s)),
else :
    print text

